spring:
  application:
    name: demo-bcp
  # ===============================
  # = SECURITY CONFIG
  # ===============================
  security:
    user:
      name: admin
      password: mila
      roles: USER